name: CI/CD Pipeline for COSC 1209

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Greeting Message
        run: echo "Hi, I am from COSC 1209 class"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for Gradle
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
